logging.level:
  liquibase: info
  org.springframework.jdbc: info
  org.springframework.web: info
  com.broadcom.springconsulting.timeservice: debug

spring:

  application:
    name: time-service

  main:
    allow-bean-definition-overriding: true

  threads:
    virtual:
      enabled: true

management:

  endpoints:
    web.exposure.include: '*'

  endpoint:
    health:
      show-details: ALWAYS
      group:
        liveness:
          show-details: always
        readiness:
          show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url:
    tracing:
      endpoint: http://otel-collector-opentelemetry-collector.monitor.svc.cluster.local:4318/v1/traces
